### ISSUE TITLE
no animal spawn

### ISSUE THREAD

**Issue by killy60** [daiguel/hunterXhunter#3]
hello I have a problem the animals do not spawn can you help me please

**Comment by White4599** [comment]
has you figured out how to solve this problem .?

**Comment by daiguel** [comment]
this is not an issue of the release, you may have a resource that despawn animal you can figure out which one by deactivating one by one and famous ressources generally don't have this problem (OX, ESX ressources), exmple of one resource that do this (gd_airport_ai_begone, ....)
