### ISSUE TITLE
hunterXhunter problème 

### ISSUE THREAD

**Issue by AftRolePlay** [daiguel/hunterXhunter#6]
Bonsoir je reçois cette erreur quand j'essaye de découper l'animal sur le point Slaughterhouse je suis sous la version Legacy 1.9.3 merci pour votre aide

https://user-images.githubusercontent.com/82605002/225763023-9c529845-a246-44bf-a860-32fb05c3c9b8.png

**Comment by daiguel** [comment]
es extended version too recent, works on 1.8 and lower
